# Generated by Django 4.2.3 on 2023-08-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mosie',
            new_name='Movie',
        ),
    ]
